Sprint1/step1
pavelborisofff/react-burger pull request #1
Opened 2023-01-07 22:53 UTC by pavelborisofff

2023-01-08 06:48 UTC, andryxxa93 requested changes
Проделана большая работа! Вы хорошо разобрались с функциональными компонентами, правильно используете useEffect.

Однако есть один момент, который необходимо исправить, чтобы работа была принята.
Сейчас вы можете этого не делать, но на финальном этапе сдачи работы это станет обязательно.

Необходимо исправить:
- Элементы хедера должны быть ссылками, а не просто текстом.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

Удачных правок!

2023-01-08 06:48 UTC, andryxxa93 commented on src/components/burger-ingredients/burger-ingredients.tsx
> +              <Tab value={tab} active={current === tab} onClick={() => setCurrent(tab)}>
**Можно лучше** 
тут можно проще `onClick={setCurrent}`

2023-01-08 06:48 UTC, andryxxa93 commented on src/components/main/main.tsx
> +// const repackData = (data: DataResponse):DataItemProps => {
**Можно улучшить**
Ненужный код лучше удалять

2023-01-08 06:48 UTC, andryxxa93 commented on src/components/main/main.tsx
> +        console.log(err);
**Можно улучшить**
Console.log нужен только для процесса разработки, перед сдачей проекта его нужно удалять, иначе она будет загружать консоль ненужной, а возможно и приватной информацией.

2023-01-08 06:48 UTC, andryxxa93 commented on src/components/main/main.tsx
> +    axios.get<DataResponse>(DataUrl)
**Можно лучше**

в дальнейшем добавятся ещё запросы к бэкенду и лучше вынести описание этих запросов в функции

Например:

```
function getIngredients() {
   return fetch(`${NORMA_API}/ingredients`)
    .then(проверка ответа)
}

```

и разместить их в отдельном файле  `utils/burger-api.js`, а не описывать запросы в самом компоненте

2023-01-13 22:53 UTC, pavelborisofff commented on src/components/main/main.tsx
> +    axios.get<DataResponse>(DataUrl)
Вынес в отдельный хук (ну или попытался) в utils/burger-api.ts

2023-01-13 22:56 UTC, pavelborisofff commented on src/components/burger-ingredients/burger-ingredients.tsx
> +              <Tab value={tab} active={current === tab} onClick={() => setCurrent(tab)}>
<img width="373" alt="image" src="https://user-images.githubusercontent.com/29525479/212433833-8a9948de-c097-4596-bd16-a6a40c5f2f2a.png">
В этом случае тайпскрипт ругается, сходу не разобрался. Но буду рад совету,  куда смотреть :)

2023-01-14 09:37 UTC, andryxxa93 approved these changes
Всё отлично! Вы можете переходить к финальному этапу работы где вам необходимо будет реализовать модальное окно.

2023-01-14 14:54 UTC, merged