Sprint5/step1
pavelborisofff/react-burger pull request #10
Opened 2023-06-10 20:40 UTC by pavelborisofff

Добрый день! Наверняка косяков полно, но в целом работает согласно ТЗ :D

2023-06-11 05:51 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Хорошая типизация проекта
- Сокеты открываются и закрываются согласно тех-заданию
- Есть проверка ошибки токена при работе работе с сокетом

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- Внешний вид модалки с заказом не соответствует макету, пожалуйста посомтрите как в фигме. Если открыть по прямой ссылке, то внешний вид правильный.
<img width="550" alt="Снимок экрана 2023-06-11 в 08 41 50" src="https://github.com/pavelborisofff/react-burger/assets/60173362/b079733c-5b75-4a32-ae0d-6062becf0472">

- В запрос на оформление заказа в хедеры необходимо передавать токен авторизации, чтобы бек понимал от кого пришел заказ
- Авторизация сбрасывается при перезагрузке страницы.
- В шапке панели навигации должны быть активна та ссылка на маршрут, где сейчас находится пользователь. Ссылка должна оставаться активной, если пользователь попадает на вложенные динамические маршруты. Например на "Историю заказов".

- Необходимо избавиться от конструкций типа - `dispatch(orderPost(body as any));`.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-06-11 05:51 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.tsx
> +      dispatch(orderPost(body as any)); // TODO: не знаю, что тут сделать, чтобы не было ошибки в TS
**Необходимо исправить**
У вас в `orderPost` требуется тип `Payload` а тут приходит другой. В функции `orderPost` нужно просто поменять тип и всё заработает.

2023-06-11 20:38 UTC, pavelborisofff commented on src/components/burger-constructor/burger-constructor.tsx
> +      dispatch(orderPost(body as any)); // TODO: не знаю, что тут сделать, чтобы не было ошибки в TS
Разобрался (надеюсь), просто было же :)

2023-06-11 23:10 UTC, pavelborisofff commented
1. Модалку поправил, просто передал другой компонент — не идеально, но если можно, то не упорствовать с вёрсткой )))
2. Добавила токен при отправке заказа
3. Починил — я токены не передавал с редусер, сейчас авторизация не сбрасывается при перегрузке. До этого циклично было, каждую перегрузку логин вываливался или появлялся из-за того, что в  SessionStorage появлялся дубль accessToken со значением null.
4. Да, не совсем то туда передавал же :)

2023-06-12 16:48 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-06-24 12:03 UTC, merged