Sprint 2/step 1
pavelborisofff/react-burger pull request #3
Opened 2023-01-18 03:25 UTC by pavelborisofff

Андрей, добрый день!

1. Использовал несколько разных контекстов вместо редусера. По началу показалось, что контекста не много, и потому можно его стэковать. Сейчас уже не считаю, что это была хорошая идея))) Но как раз свои ошибки лучше всего и запоминаются и приходит понимание ПОЧЕМУ так делать не надо. 

Я правильно понимаю, что при помощи useReducer можно подписать компонент на отслеживание изменения конкретных  атрибутов объекта?

`const reducerState = {
  isLoading: false,
  isError: false,
  data: {},
  bun: null,
  recepie: [],
  number: 0
} `

Ну что-то такого плана (без учёта методов), и та же модалка Заказа перерисовывалась бы только при изменении number, но ничего другого?

2. С редаксом же всё равно поменяется всё?

3. В src/components/burger-constructor/burger-constructor.tsx запихнул внутрь useEffect фактически хук usePostOrder из src/hooks/burger-api.ts обходя тем самым ограничение на хуки не на первом уровне компонента.
В данном случае как правильнее было бы сделать пост даты и откуда его вызывать? Хуком решил сделать потому что  явно можно переиспользовать, хотя можно наверное было просто функцией обойтись, состояние для разных контекстов сохранять, а не внутри стейта самого хука.

<img width="425" alt="image" src="https://user-images.githubusercontent.com/29525479/213074551-4f8a77c7-3760-4efe-9bb6-3cbe6c192df1.png">
<img width="571" alt="image" src="https://user-images.githubusercontent.com/29525479/213074682-09e345aa-9686-462c-aef6-0f327a35f0e6.png">

2023-01-18 05:33 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Хорошая работа.

### **Вы молодец!**

- Декомпозиция файлов по директориям соответствует описанию;
- Сборка и запуск проекта выполняются без ошибок;
- Используется контекст;

### **Но есть несколько замечаний, которые нужно исправить:**

- По макету у булок (burger-constructor) должна быть приписка `(верх)` и `(низ)`.

- Нужно очистить проект от лишних файлов, которые остались при инициализации create-react-app.

  - App.test.tsx

- Верните обёртку Strict mode, она помогает отлавливать ошибки;

- Не стоит писать 1 const/let к множествам переменным, это очень сильно портит читаемость кода;

- Если значения нет, то нужно использовать null, а не пустой объект. Проверьте во всём проекте.

- Ответы на вопросы:
  1. Да можно подписать, но вроде бы "подписка" идёт через useContext, а не useReducer. По поводу перерендеринга, в любом использующем этот контекст компоненте будет выполнен повторный рендеринг.
  
  2. Да) очень многое поменяется.
   
  3. Вы не обошли ограничение с хуками)), хук сработал до вызова useEffect компонента.
   
      Идея с хуком кул, но тогда уж лучше использовать готовые решения, например react-query), только уточните у наставника/ментора можно ли использовать такие решения. Также вы можете заметить, что функционал у хуков практически одинаковый, мне кажется лучшим вариантом тут будет просто написанием 1 общего хука для запросов, и несколько маленьких для сервисов.

### **Сделает код лучше:**

- Старайтесь не использовать any тип в typescript, т.к. он по сути просто отключает типизацию. Если не знаете какой тип применить, то сначала гуглите, а после идёте к ментору/наставнику (если не нашли ответ).

- Лучше выносить обработчики событий в отдельную функцию.

- Не спешите с typescript, в будущем вы всё равно перейдёте на него)).

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders

- В некоторых местах нарушено форматирование кода, проблемы с отступами и в некоторых местах слишком длинные строки, что затрудняет чтение кода. Об оформлении кода можно почитать здесь https://learn.javascript.ru/coding-style. Постарайтесь использовать автоматическое форматирование, это сильно экономит время. Одно из наиболее популярных дополнений для форматирования кода - Prettier (https://prettier.io/)

- Также заметил несколько слов написанных с ошибками. Чтобы это происходило реже попробуйте попользоваться расширением spell checker. https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

2023-01-18 05:33 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.tsx
> +          text={bun?.name || ''}
**Надо исправить:**

По макету у булок должна быть приписка `(верх)` и `(низ)`.

2023-01-18 05:33 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.tsx
>              <div className={`${styles.constructorItem}`} key={item._id}>
**Можно лучше:**

В след. спринтах в key лучше использовать уникальное значение для каждого ингредиента (помните что в конструкторе ингредиенты могут быть одинаковы). Лучше всего, в будущем, генерировать значение в action-creator'e (redux) при добавлении ингредиента.

2023-01-18 05:33 UTC, ArslanMustafin commented on src/components/main/main.tsx
> +        [recepie, setRecepie] = useState([] as Data[]),
**Надо исправить:**

useState это тоже дженерик - `useState<T>`, поэтому лучше указывать тип вот так - `const [data, setData] = useState<Data[]>([]);`

2023-01-18 05:33 UTC, ArslanMustafin commented on src/components/main/main.tsx
> +        [bun, setBun] = useState({} as Data),
**Надо исправить:**

Если значения нет, то нужно использовать null, а не пустой объект.

2023-01-18 05:33 UTC, ArslanMustafin commented on src/components/main/main.tsx
> +                {Object.keys(data) && <BurgerIngredients />}
**Можно лучше:**

фильтрацию/сортировку/ и т.п лучше делать в самом компоненте, где это трребуется используя useMemo. В сам компонент лучше передавать массив ингредиентов.

2023-01-18 05:33 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.tsx
> +}
**Надо исправить:** 

Вы немного не правильно используйте reducer, вот есть статейка, где показано как правильно использовать reducer https://webtricks-master.ru/react-hooks/uchim-usereducer-na-primerah-react-hooks/.

2023-01-18 05:33 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.tsx
> +  }, [data]);
**Можно лучше:**

Лучше не оставлять это в редаксе)) выглядит страшновато.
```js
const bun = data.find(ingredient =>ingredient.type === 'bun');
const ingredients = data.filter(ingredient =>ingredient.type !== 'bun');
```
Тут ещё можно useMemo добавить.
Вот так можно было бы отделить булку от ингредиентов))

2023-01-18 05:33 UTC, ArslanDev666 commented on src/utils/types.ts
> +  response: {} | null,
**Надо исправить:**

Лучше уточнить у наставника/ментора какой тип тут использовать)) т.к. тут не может быть пустой объект.

2023-01-18 05:33 UTC, ArslanDev666 commented on src/utils/constants.ts
> +const ApiUrl: string = 'https://norma.nomoreparties.space/api/';
**надо исправить:**

Константы принята писать через UPPER_CASE

2023-01-18 05:33 UTC, ArslanDev666 commented on src/hooks/burger-api.ts
> +  }, [payload]);
**Можно лучше:**

Немного не понимаю зачем делать для POST (любой запрос) запроса useEffect, его можно сделать в обычной функции.

```js
const onOrderClick = () => {
    if (!constructorItems.bun) return;

    orderBurger([
      constructorItems.bun._id,
      ...constructorItems.ingredients.map((ing) => ing._id),
      constructorItems.bun._id,
    ])
      .then((data) => {
        setOrderModalData(data);
        constructorDispatch({ type: "RESET" });
      })
      .catch((err) => {
        alert(`Ошибка при оформлении заказа: ${err.message}`);
      });
  };
```

Пример показан выше)

2023-01-18 05:33 UTC, ArslanDev666 commented on src/components/burger-ingredients/burger-ingredients.tsx
>      setModalContent(<IngredientDetails {...props} />);
**Надо исправить:**

Лучше сразу передавать контент модальному окну (как children), а не делать это через setState.

2023-01-18 08:04 UTC, pavelborisofff commented on src/components/burger-constructor/burger-constructor.tsx
> +          text={bun?.name || ''}
Оу, точно, не заметил

2023-01-18 08:05 UTC, pavelborisofff commented on src/components/burger-constructor/burger-constructor.tsx
>              <div className={`${styles.constructorItem}`} key={item._id}>
Ага, понял, да, их же действительно несколько штук может быть

2023-01-20 00:27 UTC, pavelborisofff commented on src/components/main/main.tsx
> +        [recepie, setRecepie] = useState([] as Data[]),
Постарался привести типизацию к нормальному виду (насколько смог)

2023-01-20 00:27 UTC, pavelborisofff commented on src/components/main/main.tsx
> +        [bun, setBun] = useState({} as Data),
Тоже поправил

2023-01-20 00:29 UTC, pavelborisofff commented on src/components/burger-constructor/burger-constructor.tsx
> +  }, [data]);
Это токмо  ради генерации случайного заказа :) тут можно закрыть глаза и не смотреть

2023-01-20 00:38 UTC, pavelborisofff commented on src/components/main/main.tsx
> +                {Object.keys(data) && <BurgerIngredients />}
В точности с ТЗ!

_3. Подсчёт итоговой стоимости бургера

Выводите стоимость бургера динамически в зависимости от тех ингредиентов, которые находятся в конструкторе. Мы рекомендуем попрактиковаться с использованием хука useReducer, но это необязательное требование, а лишь временное решение._


Я понимаю, что ретушер больше для хранения состояния, а не для подобных вычислений :D

2023-01-20 00:52 UTC, pavelborisofff commented on src/utils/constants.ts
> +const ApiUrl: string = 'https://norma.nomoreparties.space/api/';
Переименовал и эндпоинты в енум запихнул

2023-01-20 21:55 UTC, pavelborisofff commented on src/components/burger-ingredients/burger-ingredients.tsx
>      setModalContent(<IngredientDetails {...props} />);
Да оно чилдреном и передаётся. УБрал только сайт из hooks/modal-control.ts


Как из handleOrder правильно modalContent поменять? через setState же?

2023-01-20 21:56 UTC, pavelborisofff commented on src/hooks/burger-api.ts
> +  }, [payload]);
у меня GET-запрос был тоже через useEffect, я поменял это

2023-01-20 22:18 UTC, pavelborisofff commented on src/components/burger-constructor/burger-constructor.tsx
> +}
но работает же! :D


Исправил, типизировал

2023-01-20 22:31 UTC, pavelborisofff commented on src/utils/types.ts
> +  response: {} | null,
Насколько смог поправил.


ТС за пару уроков не выучить, так что я лучше сразу попробую. На него реально времени полно уходит разобраться и найти вменяемый вариантов документации/интернете

2023-01-20 22:39 UTC, pavelborisofff commented
Арслан, спасибо за комменты!

> Старайтесь не использовать any тип в typescript, т.к. он по сути просто отключает типизацию. Если не знаете какой тип применить, то сначала гуглите, а после идёте к ментору/наставнику (если не нашли ответ).

ТС отнимает больше времени, чем сам код :) и да, Гугл, конечно и документация
Но часто варианты ооооочень плохие находятся, которые типизацию убивают в итоге.

> Если значения нет, то нужно использовать null, а не пустой объект. Проверьте во всём проекте.
В useState везде где смог поставил null или первоначальное значение, чтобы без объектов


За расширения спасибо, но VS Code с ними начинает глючить жутко :( отваливаются быстрые клавиши и даже cmd+C/cmd+V о_О Буду разбираться.

2023-01-21 05:42 UTC, ArslanDev666 commented on src/components/main/main.tsx
> +  const [recipe, setRecipe] = useState<Data[]>([] as Data[]);
**Можно лучше:**

Здесь и если есть, то в похожих местах)

`as Data[]` - тут не нужно, т.к. массив может быть пустым, от этого его тип не поменяется, поэтому явно тут приводить ничего не нужно))

2023-01-21 05:42 UTC, ArslanDev666 commented on src/utils/constants.ts
> +const ApiUrl: string = 'https://norma.nomoreparties.space/api/';
Ну enums на самом деле не так уж часто встречаются в проектах (повезёт если 2-3 раза увидите), но тут думаю допустимо использовать)) хотя, я бы предпочёл простой массив, или даже объект.

2023-01-21 05:51 UTC, ArslanDev666 commented on src/hooks/burger-api.ts
> +const BurgerApi = () => {
**Можно лучше:**

Название файла, и имя самого custom хука принято писать с приставкой `use`) например `useMount, useBurgerApi`.

И ещё возможно всё таки вам стоит сделать сервисы для api. А хук использовать как manager))
Вот есть прекрасная статья, также советую почитать комментарии: https://dev.to/patrixr/react-writing-a-custom-api-hook-l16.

2023-01-21 05:53 UTC, ArslanDev666 commented on src/components/burger-ingredients/burger-ingredients.tsx
>      <>
**Можно лучше:**
эта обёртка `<>` лишняя, оборачивать в React.Fragment требуется, только если в компонент содержит несколько невложенных блоков, например

```
<>
  <div>.....</div>
  <div>.....</div>
</>

```

[https://ru.reactjs.org/docs/fragments.html](https://ru.reactjs.org/docs/fragments.html)

2023-01-21 05:56 UTC, ArslanDev666 commented on src/components/burger-ingredients/burger-ingredients.tsx
> +};
**Можно лучше:**

Мне кажется вы тут немного перестарались с разделением на компоненты, IngredientsGroups лучше убрать (сделать всё в BurgerIngredients), а Group переименовать в ingedients-category (IngedientsCategory) и вынести в отдельный файлик, и папку))

2023-01-21 05:58 UTC, ArslanDev666 commented on src/components/burger-ingredients/ingredient.tsx
> +const Ingredient = (props: Data) => {
**Можно лучше:**

Передавайте сюда цельный объект ингредиента, а не все его поля)) поверьте так намного легче оперировать с данными)

2023-01-21 05:59 UTC, ArslanDev666 commented on src/components/burger-ingredients/ingredient.tsx
> +      {"" + props.type === "bun" && bun?._id === props._id && (
**Можно лучше:**

Сравнение с enum происходит следующим образом:

```js
props.type === Tabs.bun
```

2023-01-21 06:11 UTC, ArslanDev666 commented on src/components/burger-ingredients/ingredient.tsx
> +      {modalContent && <Modal
**Надо исправить**

не нужно передавать условие открытия в попап и размещать логику открытия там. Рендерите компонент попапа только, если он открыт, используя для этого условный рендеринг

```js
{isOpen && (
    компонент открываемого попапа
)}
``

2023-01-21 06:15 UTC, ArslanDev666 commented on src/components/burger-ingredients/ingredient.tsx
> +      </Modal>}
**Надо исправить:**

касается этого замечания - https://github.com/pavelborisofff/react-burger/pull/3#discussion_r1073108504;
Ниже оптимальный вариант использования модальный окон)) 

```js
  {isOpenIngredientDetails && (
    <Modal
      onClose={handleCloseIngredientDetails} // просто вынесли обработчик события в отдельную функцию
      header="Что-то"
    >
        <IngredientDetails ingredient={props.ingredient} />
    </Modal>}
```

Вот что я имел ввиду, когда говорил, что лучше сразу передавать контент модального окна, а не ставить его через setState.

2023-01-21 06:16 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Хорошая работа.

### **Вы молодец! Работа принята. Удачи в дальнейшем обучении.**

- Практически все замечания с прошлого ревью были исправлены.

Комменты что-то не захотели подтягиваться :( но думаю вы поймёте где начало)

По поводу расширений:
- Да, возможны зависания (хотя я такое только на загруженной винде встречал, на чистой и на маке такого не замечал), тут по желанию))
- На маке клавиши стабильно работают))

2023-01-21 08:14 UTC, pavelborisofff commented on src/utils/constants.ts
> +const ApiUrl: string = 'https://norma.nomoreparties.space/api/';
Я немного питоновод, привык к FastAPI+pydantic, там ваще всё можно запихнуть в типизацию/валидацию/описание. И проще, чем в ТС, кстати :D

2023-01-21 08:15 UTC, pavelborisofff commented on src/components/main/main.tsx
> +  const [recipe, setRecipe] = useState<Data[]>([] as Data[]);
Да, недоглядел, старый вариант остался. С типизацией благодаря вашим комментам чуть подробнее ознакомился :)

2023-01-21 08:16 UTC, pavelborisofff commented on src/components/burger-ingredients/burger-ingredients.tsx
>      <>
Да, про <></> знаю, надо мне чуть меньше в ночи кодить для меньшего количества неряшливостей

2023-02-21 19:03 UTC, merged